### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [DIY-Machines/RC-Domino-Machine-V1#2]
Hello!

I found link to this project from https://hackaday.com/2021/01/01/domino-layer-lets-you-focus-on-toppling/

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by DIY-Machines** [comment]
Hi.

I've added an MIT License to the project. 

Thanks for checking.
Lewis
